version: '3.1'
services:
  postgresql:
    image: postgres:latest
    ports:
    - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_USER=app
      - POSTGRES_DB=db
